trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- task: CMake@1
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    cmakeArgs: '..'
    
- task: CMake@1
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    cmakeArgs: '--build .'    

- task: PublishBuildArtifacts@1
