trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
      artifactSuffix: 'ubuntu'
    #mac:
    #  imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'
      artifactSuffix: 'ubuntu'

pool:
  vmImage: $(imageName)

steps:
- task: CMake@1
  inputs:
    workingDirectory: 'build'
    cmakeArgs: '..'
    
- task: CMake@1
  inputs:
    workingDirectory: 'build'
    cmakeArgs: '--build .'    

- task: CopyFiles@2
  inputs:
    contents: 'build/**/*plctag.*'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: CopyFiles@2
  inputs:
    contents: 'src/lib/libplctag.h'
    targetFolder: $(Build.ArtifactStagingDirectory)
    
- publish: '$(Build.ArtifactStagingDirectory)'
  artifact: LibPLCTag-$(artifactSuffix)
